include:
  - project: "gnome/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

flatpak:
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master"
  variables:
    MANIFEST_PATH: "org.gnome.SoundRecorder.json"
    BUNDLE: "sound-recorder-dev.flatpak"
    FLATPAK_MODULE: "gnome-sound-recorder"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.SoundRecorderDevel"
  extends: .flatpak

nightly:
  extends: ".publish_nightly"

eslint:
  image: registry.gitlab.gnome.org/gnome/gjs:fedora.static-analysis

  variables:
    LINT_LOG: "eslint-report.txt"
  script:
    - eslint -o $LINT_LOG --no-color src || { cat $LINT_LOG; false; }
  artifacts:
    paths:
      - ${LINT_LOG}
    when: on_failure
